services:
  - type: web
    name: n8n
    env: docker
    region: singapore
    plan: starter
    branch: main
    numInstances: 1
    healthCheckPath: /healthz
    rootDir: .
    envVars:
      - key: N8N_HOST
        value: n8n.suzurin.me
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_PORT
        value: 80
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: n8n-db
          property: database
      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: n8n-db
          property: host
      - key: DB_POSTGRESDB_PORT
        fromDatabase:
          name: n8n-db
          property: port
      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: n8n-db
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8n-db
          property: password

databases:
  - name: n8n-db
    region: singapore
    plan: free
